# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "Push a new build to TestFlight"
  lane :deploy do
    package = load_json(json_path: File.join(Dir.pwd, "..", "package.json"))
    version = package["version"]

    # Get latest certs appstore
    match(type: 'appstore')

    build_app(workspace: "./ios/reactnativetemplate.xcworkspace", scheme: "reactnativetemplate")

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"]
    )

    upload_to_testflight(skip_waiting_for_build_processing: true)

    slack(message: "New React Native Template mobile app version #{version} was uploaded to TestFlight!", slack_url: ENV["SLACK_WEBHOOK_URL"])
  end
end

platform :android do
  desc "Push a new build to Play Store"
  lane :deploy do
    package = load_json(json_path: File.join(Dir.pwd, "..", "package.json"))
    version = package["version"]

    releaseFilePath = File.join(Dir.pwd, "../android", "release-key.keystore")

    gradle(task: 'clean', project_dir: 'android/')

    gradle(
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => ENV["ANDROID_KEY_STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_KEY_ALIAS_PASSWORD"],
      },
      project_dir: 'android/'
    )

    upload_to_play_store(
      track: 'internal',
      release_status: 'draft'
    )

    slack(message: "New React Native Template mobile app version #{version} was uploaded to Google Play!", slack_url: ENV["SLACK_WEBHOOK_URL"])
  end
end
